# Generated by Django 3.2 on 2021-05-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='author',
            field=models.IntegerField(default=1, verbose_name='ID Автора'),
            preserve_default=False,
        ),
    ]
