# Generated by Django 3.2 on 2021-05-12 07:10

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember', '0003_alter_memory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='location',
            field=places.fields.PlacesField(default=1, max_length=255, verbose_name='Место на карте'),
            preserve_default=False,
        ),
    ]
